### ISSUE TITLE
Specifying seednode as tag in mused command and config file at same time crashes node

### ISSUE THREAD

**Issue by educatedwarrior** [themuseblockchain/Muse-Source#4] opened 2017-08-14 12:10 UTC
If you specify seed node when you start the node and put it in the config file at the same time, mused crashes.

**Comment by Tadasu85** [comment] 2017-09-18 11:28
This is not a bug it is simply convention, you have the option to specify on launch when creating your config.ini once you have done so add your props to the config.ini then do not use the extra props on launch. Please close guys thank you EW for the contribution tho :)

**Comment by pmconrad** [comment] 2017-11-12 15:56
You can specify seed nodes on the command line as well as in the config file.
What makes the node crash is if you specify a seed node twice (no matter where). I'd call this a bug.

**Comment by pmconrad** [comment] 2018-01-17 14:03
Fixed in latest develop.

**Closed as completed by pmconrad** 2018-01-17 14:03 UTC
Labels: bug
